const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
const GET_SUGGESTION_LIST = "GET_SUGGESTION_LIST";
const CLEAR_PRODUCTS_BY_CATEGORY = "CLEAR_PRODUCTS_BY_CATEGORY";
const GET_CATEGORY = "GET_CATEGORY";
const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export { 
    GET_SEARCH_RESULTS,
    GET_SUGGESTION_LIST,
    GET_CATEGORY, 
    GET_PRODUCT_BY_CATEGORY,
    CLEAR_PRODUCTS_BY_CATEGORY,
    GET_ALL_PRODUCTS
 };